### ISSUE TITLE
Week1 作業

### ISSUE THREAD

**Issue by FrankyWu** [rocodev/june-artstore#15]
Heroku位置
http://franky-store.herokuapp.com/

**Comment by xdite** [comment]
應該是要交 repo 噢

**Comment by FrankyWu** [comment]
請問一下Xdite 有昨天上課中修改完的投影片檔案嗎?

沒有拍到怎麼生成AASM

感恩

Best Regards,

吳少龍 (Franky)
Founder
5irehands Studio

phone: 0921177643
Email: forefeel741114@gmail.com noni2she@gmail.com

2014-06-17 11:25 GMT+08:00 Yi-Ting Cheng notifications@github.com:
